services:
  - type: web
    name: api-bazar-universal
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt && python data/init_db.py"
    startCommand: "python start.py"
    envVars:
      - key: ENVIRONMENT
        value: production
      - key: CORS_ORIGINS
        value: "*"
  
  - type: pserv
    name: bazar-database
    plan: free
    databaseName: bazar_universal
    databaseUser: bazar_user
